# Generated by Django 2.2.4 on 2020-04-03 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Adicionales')),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Adicionales')),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Quincenal', 'Quincenal')], max_length=50, verbose_name='Tipo de nomina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('additionals', models.ManyToManyField(related_name='additionals', to='payroll.Additional')),
                ('discounts', models.ManyToManyField(related_name='discounts', to='payroll.Discount')),
                ('law_discounts', models.ManyToManyField(related_name='law_discounts', to='payroll.LawDiscount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
