# Generated by Django 2.2.4 on 2020-04-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfiguration',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_configuration', to='users.Organization'),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='type_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='payroll.TypePayroll'),
        ),
        migrations.AddField(
            model_name='discount',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.Organization'),
        ),
        migrations.AddField(
            model_name='additional',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='users.Organization'),
        ),
    ]
