# Generated by Django 2.2.4 on 2020-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200211_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepayroll',
            name='name',
            field=models.CharField(choices=[('Quincena', 'Quincenal')], max_length=50, verbose_name='Tipo de nomina'),
        ),
    ]
