# Generated by Django 2.2.4 on 2020-04-09 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('collaborator', '0002_auto_20200403_0220'),
        ('payroll', '0002_auto_20200403_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawDiscountOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('law_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.LawDiscount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_discounts', to='users.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Count')),
                ('day_apply', models.IntegerField(verbose_name='Day to apply periods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='additionals',
        ),
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='law_discounts',
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='active_month',
            field=models.IntegerField(default=6, verbose_name='Active Months'),
        ),
        migrations.AddField(
            model_name='typepayroll',
            name='count_mount',
            field=models.IntegerField(default=2, verbose_name='Count on Month'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_apply', models.DateField(verbose_name='Date to apply')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollConfiguration')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Period')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.StatusPayroll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='additional',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.Organization'),
        ),
        migrations.CreateModel(
            name='PayrollCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('additionals', models.ManyToManyField(to='payroll.Additional')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='collaborator.Collaborator')),
                ('discounts', models.ManyToManyField(to='payroll.Discount')),
                ('law_discounts', models.ManyToManyField(to='payroll.LawDiscountOrganization')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Payroll')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
