# Generated by Django 2.2.4 on 2020-02-12 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20200211_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=120)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='discounts',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='law_discounts',
            field=models.ManyToManyField(related_name='law_discounts', to='payroll.LawDiscount'),
        ),
    ]
