# Generated by Django 2.2.4 on 2020-02-12 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200207_0447'),
        ('payroll', '0005_auto_20200212_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=120)),
                ('name', models.CharField(max_length=50, verbose_name='Adicionales')),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='discount',
            field=models.ManyToManyField(related_name='discounts', to='payroll.Discount'),
        ),
    ]
