# Generated by Django 2.2.4 on 2020-03-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.Level'),
        ),
    ]
