# Generated by Django 2.2.4 on 2020-03-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('collaborator', '0002_auto_20200327_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalarea',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
            preserve_default=False,
        ),
    ]
