# Generated by Django 2.2.4 on 2020-03-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_auto_20200327_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Base salary'),
            preserve_default=False,
        ),
    ]
